jobs:
  build:
    name: Stage release to Artifactory
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Capture release version
      run: echo RELEASE_VERSION=${{ github.event.inputs.releaseVersion }} >> $GITHUB_ENV
    - continue-on-error: true
      name: Update release version
      run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$RELEASE_VERSION
    - continue-on-error: true
      name: Enforce release rules
      run: mvn org.apache.maven.plugins:maven-enforcer-plugin:enforce -Drules=requireReleaseDeps
    - continue-on-error: true
      env:
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      name: Build with Maven and deploy to Artifactory staging repository
      run: mvn -P artifactory-staging -s settings.xml --batch-mode -Dmaven.test.skip=true
        deploy
name: Artifactory Staging
on:
  repository_dispatch:
    types: trigger-ga___artifactory-staging.yml
