jobs:
  code-quality-analysis:
    name: code quality analysis report
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Analyse test coverage with Jacoco
      run: mvn -P test-coverage verify
    - continue-on-error: true
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: github.repository == 'spring-projects/spring-batch'
      name: Analyse code quality with Sonar
      run: mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
name: Continuous inspection build
on:
  repository_dispatch:
    types: trigger-ga___continuous-inspection.yml
