jobs:
  build:
    name: Build branch
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      env:
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      name: Build with Maven and deploy to Artifactory
      run: mvn -s settings.xml --batch-mode --update-snapshots deploy
    - continue-on-error: true
      name: Generate Java docs
      run: mvn javadoc:aggregate
    - continue-on-error: true
      name: Generate Assembly
      run: mvn assembly:single
      working-directory: spring-batch-docs
    - continue-on-error: true
      name: Capture project version
      run: echo PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version --quiet
        -DforceStdout) >> $GITHUB_ENV
    - continue-on-error: true
      env:
        DOCS_SSH_HOST_KEY: ${{ secrets.DOCS_SSH_HOST_KEY }}
        DOCS_SSH_KEY: ${{ secrets.DOCS_SSH_KEY }}
      name: Setup SSH key
      run: 'mkdir "$HOME/.ssh"

        echo "$DOCS_SSH_KEY" > "$HOME/.ssh/key"

        chmod 600 "$HOME/.ssh/key"

        echo "$DOCS_SSH_HOST_KEY" > "$HOME/.ssh/known_hosts"

        '
    - continue-on-error: true
      env:
        DOCS_HOST: ${{ secrets.DOCS_HOST }}
        DOCS_PATH: ${{ secrets.DOCS_PATH }}
        DOCS_USERNAME: ${{ secrets.DOCS_USERNAME }}
      name: Deploy Java docs
      run: 'unzip spring-batch-$PROJECT_VERSION-javadocs.zip

        ssh -i $HOME/.ssh/key $DOCS_USERNAME@$DOCS_HOST "cd $DOCS_PATH && mkdir -p
        $PROJECT_VERSION/api"

        scp -i $HOME/.ssh/key -r api $DOCS_USERNAME@$DOCS_HOST:$DOCS_PATH/$PROJECT_VERSION/api

        '
      working-directory: spring-batch-docs/target
name: CI/CD build
on:
  repository_dispatch:
    types: trigger-ga___continuous-integration.yml
