jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Capture release version
      run: echo RELEASE_VERSION=${{ github.event.inputs.releaseVersion }} >> $GITHUB_ENV
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Update release version
      run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$RELEASE_VERSION
    - continue-on-error: true
      name: Generate Java docs
      run: mvn javadoc:aggregate
    - continue-on-error: true
      name: Generate Assembly
      run: mvn assembly:single
      working-directory: spring-batch-docs
    - continue-on-error: true
      env:
        DOCS_SSH_HOST_KEY: ${{ secrets.DOCS_SSH_HOST_KEY }}
        DOCS_SSH_KEY: ${{ secrets.DOCS_SSH_KEY }}
      name: Setup SSH key
      run: 'mkdir "$HOME/.ssh"

        echo "$DOCS_SSH_KEY" > "$HOME/.ssh/key"

        chmod 600 "$HOME/.ssh/key"

        echo "$DOCS_SSH_HOST_KEY" > "$HOME/.ssh/known_hosts"

        '
    - continue-on-error: true
      env:
        BATCH_SCHEMA_PATH: ${{ secrets.BATCH_SCHEMA_PATH }}
        DOCS_HOST: ${{ secrets.DOCS_HOST }}
        DOCS_PATH: ${{ secrets.DOCS_PATH }}
        DOCS_USERNAME: ${{ secrets.DOCS_USERNAME }}
        INTEGRATION_SCHEMA_PATH: ${{ secrets.INTEGRATION_SCHEMA_PATH }}
      name: Deploy Java docs and xsd schemas
      run: 'unzip spring-batch-$RELEASE_VERSION-javadocs.zip

        ssh -i $HOME/.ssh/key $DOCS_USERNAME@$DOCS_HOST "cd $DOCS_PATH && mkdir -p
        $RELEASE_VERSION/api"

        scp -i $HOME/.ssh/key -r api $DOCS_USERNAME@$DOCS_HOST:$DOCS_PATH/$RELEASE_VERSION/api


        unzip spring-batch-$RELEASE_VERSION-schemas.zip

        scp -i $HOME/.ssh/key batch/*.xsd $DOCS_USERNAME@$DOCS_HOST:$BATCH_SCHEMA_PATH

        scp -i $HOME/.ssh/key batch-integration/*.xsd $DOCS_USERNAME@$DOCS_HOST:$INTEGRATION_SCHEMA_PATH

        '
      working-directory: spring-batch-docs/target
name: Documentation Upload
on:
  repository_dispatch:
    types: trigger-ga___documentation-upload.yml
