jobs:
  build:
    name: Build an extension
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        ref: main
        repository: spring-projects/spring-batch-extensions
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build extension with Maven
      run: mvn -B package --file pom.xml
      working-directory: ${{ github.event.inputs.extension }}
name: Spring Batch Extension Build
on:
  repository_dispatch:
    types: trigger-ga___extension-build.yml
